language: java
addons:
    ssh_known_hosts: 35.157.216.139
before_install:
    - bash .scripts/install.sh
after_success:
    - bash .scripts/deploy.sh
after_script:
    - bash .scripts/runJava.sh
notifications:
    slack: ohtupartio:9Fqci61YwcZE8Wj25AzaV2ID
