language: java
addons:
    ssh_known_hosts: 34.243.147.82
before_install:
- openssl aes-256-cbc -K $encrypted_0521f70a21ab_key -iv $encrypted_0521f70a21ab_iv
  -in deploy.pem.enc -out deploy.pem -d
rm deploy.pem.enc
chmod 600 deploy.pem
mv deploy.pem ~/.travis/id_rsa
after_success:
    - bash .scripts/deploy.sh
